/** @format */

export default [
  "ala delta",
  "acrobacia",
  "acuatlon",
  "aerobic",
  "aikido",
  "ajedrez",
  "alpinismo",
  "artes marciais",
  "atletismo",
  "automobilismo",
  "baloncesto",
  "balonman",
  "billar",
  "billarda",
  "birlos",
  "bobsleigh",
  "bodyboard",
  "boxeo",
  "badminton",
  "beisbol",
  "caza",
  "ciclismo",
  "colombofilia",
  "corfebol",
  "criquet",
  "croquet",
  "cuadratlon",
  "curling",
  "danza deportiva",
  "dardos",
  "futbol",
  "futbol playa",
  "futbol sala",
  "golf",
  "gimnasia",
  "gimnasia ritmica",
  "halterofilia",
  "hipica",
  "hockey a patins",
  "hockey sobre hierba",
  "hockey sobre hielo",
  "hockey",
  "hurling",
  "judo",
  "karate",
  "kendo",
  "kickboxing",
  "karting",
  "kung Fu",
  "lacrosse",
  "lucha",
  "lucha tradicional gallega",
  "luciadas extremas",
  "mumerjo",
  "motociclismo",
  "motonautica",
  "mhuai thay",
  "natacion",
  "octopush",
  "orientacion",
  "paracaidismo",
  "parapente",
  "parkour",
  "patinaxe",
  "paintball",
  "pelota",
  "pelota valenciana",
  "pelota vasca",
  "pentatlon moderno",
  "pesca deportiva",
  "petanca",
  "piragüismo",
  "polo",
  "remo",
  "rugby",
  "salto de trampolin",
  "sendeirismo",
  "softbol",
  "shinty",
  "skateboard",
  "skeleton",
  "snowboard",
  "speedball",
  "squash",
  "sumo",
  "superbikes",
  "surf",
  "tenis",
  "tenis de mesa",
  "tiro",
  "tiro con arco",
  "triatlon",
  "taekwondo",
  "ultralixeiros",
  "vela",
  "voleibol",
  "volei playa",
  "valetudo",
  "waterpolo",
  "windsurf",
  "wushu",
  "win tsun",
  "xadrez",
  "ximnasia",
  "ximnasia ritmica",
  "esgrima",
  "espeleoloxia",
  "esqui",
  "equitacion",
];
